banking/bankapp/urls.py
from . import views
from django.urls import path

app_name='bankapp'
urlpatterns= [
    path('',views.home,name='home'),
    path('register/',views.registration,name='register'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('content/',views.content,name='content'),


    path('add/',views.person_create_view,name='person_add'),

    path('ajax/load_branches/',views.load_branches,name='load_branches'),
]

banking/banking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bankapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

banking/bankapp/models.py
from turtle import mode

from django.db import models

# Create your models here.
class District(models.Model):
    district_name=models.CharField(max_length=250,unique=True)

    def __str__(self):
        return self.district_name
class Branch(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    branch_name=models.CharField(max_length=250,unique=True)

    def __str__(self):
        return self.branch_name

class NewMember(models.Model):
    name = models.CharField(max_length=200)
    dob = models.DateField()
    age = models.CharField(max_length=3)
    gender_select=(('m','Male'),('f','Female'),('o','Others'))
    gender = models.CharField(max_length=10,choices=gender_select,default=None)
    phone = models.CharField(max_length=10)
    email = models.EmailField(max_length=200)
    address = models.TextField(max_length=250)
    district = models.ForeignKey(District, on_delete=models.SET_NULL,blank=True,null=True)
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL,blank=True,null=True,default=None)
    account_select = (('current','Current Account'),('savings','Savings Account'),('nri','NRI Account'))
    account = models.CharField(max_length=50, choices=account_select)
    # materials_select = (('cheque','Cheque Book'),('credit','Credit Card'),('debit','Debit Card'))
    materials = models.CharField(max_length=100,default=None)

    def __str__(self):
        return self.name

banking/bankapp/forms.py
from django import forms
from django.forms import TextInput,ChoiceField
from .models import NewMember,Branch

MATERIAL_CHOICES = [
    ('cheque','Cheque Book'),
    ('debit', 'Debit Card'),
    ('credit','Credit Card')
]
class NewMemberForm(forms.ModelForm):
    materials = forms.MultipleChoiceField(choices=MATERIAL_CHOICES,widget=forms.CheckboxSelectMultiple)
    class Meta:
        model = NewMember
        fields = '__all__'

        widgets = {
            'name': forms.TextInput(),
            'dob' : forms.DateInput(attrs={'type':'date'}),
            'gender': forms.RadioSelect(),
            'email' :forms.EmailInput(),
            'materials' : forms.TextInput(),

            # 'country': forms.ChoiceField(attrs={'class': "php-email-form"})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['branch'].queryset = Branch.objects.none()

        if 'district' in self.data:
            try:
                district_id = int(self.data.get('district'))
                self.fields['branch'].queryset = Branch.objects.filter(district_id=district_id).order_by('branch_name')
            except (ValueError,TypeError):
                pass
        elif self.instance.pk:
            self.fields['branch'].queryset = self.instance.district.branch_set.order_by('branch_name')

banking/bankapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import CreateView

from .forms import NewMemberForm
from .models import District, Branch, NewMember


# # Create your views here.
#
#
def person_create_view(request):
    form = NewMemberForm()
    if request.method == 'POST':
        # print(request.POST.get('materials'))
        form = NewMemberForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request,"Application Accepted")
            return redirect('bankapp:person_add')
        else:
            messages.info(request,"Failed")
    return render(request,'form.html',{'form':form})



def home(request):
    district_list=District.objects.all()
    return render(request,'index.html',{'d_list':district_list})
    # return HttpResponse("hello")
def registration(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        cpassword=request.POST['cpassword']
        if password == cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,"Username already exists")
                return redirect('bankapp:register')
            else:
                user=User.objects.create_user(username=username,password=password)
                user.save()
                print("user created")
                return redirect('bankapp:login')
        else:
            messages.info(request,"Password not matching")
            return redirect('bankapp:register')
    return render(request,'register.html')
def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('bankapp:content')
        else:
            messages.info(request,"Invalid Credentials")
            return redirect('bankapp:login')
    return render(request,'login.html')

def content(request):
    # form = NewMemberForm()
    # if request.method == 'POST':
    #     form = NewMemberForm(request.POST)
    #     if form.is_valid():
    #         form.save()
    #         return redirect('content')
    #     else:
    #         return HttpResponse("Failed")
    # return render(request,'content.html',{'form':form})
    return render(request,'content.html')
def logout(request):
    auth.logout(request)
    return redirect('/')

#ajax


def load_branches(request):

    district_id = request.GET.get('district_id')
    branches = Branch.objects.filter(district_id=district_id)
    return render(request,'dropdown_list.html',{'branches':branches})

banking/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Gp Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Gp
  * Updated: Sep 18 2023 with Bootstrap v5.3.2
  * Template URL: https://bootstrapmade.com/gp-free-multipurpose-html-bootstrap-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>
<body>
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top ">
    <div class="container d-flex align-items-center justify-content-lg-between">

      <h1 class="logo me-auto me-lg-0"><a href="index.html">Yourbank<span>.</span></a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto me-lg-0"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      {% include 'navbar.html' %}


    </div>
  </header><!-- End Header -->

{% block content %}
{% endblock %}



<!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6">
            <div class="footer-info">
              <h3>yourbank<span>.</span></h3>
              <p>
                A108 Adam Street <br>
                NY 535022, USA<br><br>
                <strong>Phone:</strong> +1 5589 55488 55<br>
                <strong>Email:</strong> info@example.com<br>
              </p>
              <div class="social-links mt-3">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
              </div>
            </div>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>

          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>YourBank</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/gp-free-multipurpose-html-bootstrap-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

banking/templates/content.html
{% extends 'base.html' %}
{% load static %}
{% block  content %}

<section id="hero" class="d-flex align-items-center justify-content-center">
    <div class="container" data-aos="fade-up">

      <div class="row justify-content-center" data-aos="fade-up" data-aos-delay="150">
        <div class="col-xl-6 col-lg-8">
          <h1>Powerful Banking Solutions With YourBank<span>.</span></h1>
          <h2>We are team to make your banking easy.</h2>
        </div>
      </div>

      <div class="container d-flex align-items-center justify-content-center" data-aos="zoom-in" data-aos-delay="250">
        <a href="{% url 'bankapp:person_add' %}" class="get-started-btn scrollto">Know More</a>
      </div>

    </div>
  </section>


{% endblock %}

banking/templates/dropdown_list.html
{% load static %}


{% for branch in branches %}
<option value="{{ branch.pk }}">{{ branch.branch_name }}</option>
{% endfor %}

banking/templates/form.html
{% extends 'base.html' %}
{% load static %}
{% block  content %}

  <section id="hero" class="d-flex align-items-center justify-content-center">
    <div class="container" data-aos="fade-up">

      <div class="row justify-content-center" data-aos="fade-up" data-aos-delay="150">
        <div class="col-xl-6 col-lg-8">
          <h1>Powerful Banking Solutions With YourBank<span>.</span></h1>

        </div>
      </div>



    </div>
  </section>
<section id="contact" class="contact">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Details Form</h2>
        </div>
      </div>

<!--            <div class="row mt-5">-->
<!--              <div class="col-lg-6 mt-5 mt-lg-6">-->

    <div class="container">
        <div class="row">

            <form action="" method="POST" id="memberForm" data-branches-url="{% url 'bankapp:load_branches' %}">
              {% csrf_token %}
              <div class="row">
                   <div class="form-control">
                        <div class="col-md-6 form-group ">
                             {{ form.as_p }}
                        </div>
                       <div class="php-email-form">
                           <button type="submit">Submit</button>
                           <button type="submit"><a style="color:black;" href="{% url 'bankapp:logout' %}">Logout</a></button>
                       </div>
                   </div>
              </div>
            </form>
        </div>
    </div>
</section>

            <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_district").change(function () {
        const url = $("#memberForm").attr("data-branches-url");
        const districtId = $(this).val();

        $.ajax({
            url: url,
            data: {
                'district_id': districtId
            },
            success: function (data) {
                $("#id_branch").html(data);
                      }
        });

    });
</script>



{% for msg in messages %}
{{msg}}
<p><a href="{% url 'bankapp:home' %}">Home</a></p>
{% endfor %}

{% endblock %}

banking/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block  content %}

  <section id="hero" class="d-flex align-items-center justify-content-center">
    <div class="container" data-aos="fade-up">

      <div class="row justify-content-center" data-aos="fade-up" data-aos-delay="150">
        <div class="col-xl-6 col-lg-8">
          <h1>Powerful Banking Solutions With YourBank<span>.</span></h1>
          <h2>Login to know more</h2>
        </div>
      </div>



    </div>
  </section>
<section id="contact" class="contact">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Login</h2>
            <div class="row mt-5">
              <div class="col-lg-8 mt-5 mt-lg-6">



            <form action="" method="post" role="form" class="">
              {% csrf_token %}
              <div class="row">
                <div class="col-md-8 form-group php-email-form">
                  <input type="text" name="username" class="form-control" id="name" placeholder="Username" required>
                </div>
                <div class="col-md-8 form-group mt-3 mt-md-4 php-email-form">
                  <input type="password" class="form-control" name="password" id="password" placeholder="Password" required>
                </div>
              </div>
              <div class="php-email-form"><button type="submit">Login</button></div>
              <div class="member-info">New member...? <a href="{% url 'bankapp:register' %}">Register</a></div>
            </form>
              </div>
          </div>
        </div>
      </div>
</section>
{% for msg in messages %}
  {{msg}}
{% endfor %}

{% endblock %}

banking/templates/navbar.html
<nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'bankapp:home' %}">Home</a></li>
          <li><a class="nav-link scrollto" href="#about">About</a></li>
            {% if user.is_authenticated %}
            <li><a class="nav-link scrollto">Hello, {{user.username}}</a></li>
            <li><a class="nav-link scrollto" href="{% url 'bankapp:logout' %}">Logout</a></li>
            {% else %}
          <li><a class="nav-link scrollto" href="{% url 'bankapp:login' %}">Login</a></li>
          <li><a class="nav-link scrollto " href="{% url 'bankapp:register' %}">Register</a></li>
            {% endif %}
          <li class="dropdown {% if 'bankapp' in request.path %} active {% endif %}"><a href="#"><span>Branches</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              {% for i in d_list %}
              <li><a href="https://en.wikipedia.org/wiki/{{i.district_name}}">{{i.district_name}}</a></li>
              {% endfor %}
            </ul>
          </li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

banking/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block  content %}

  <section id="hero" class="d-flex align-items-center justify-content-center">
    <div class="container" data-aos="fade-up">

      <div class="row justify-content-center" data-aos="fade-up" data-aos-delay="150">
        <div class="col-xl-6 col-lg-8">
          <h1>Powerful Digital Solutions With Gp<span>.</span></h1>
          <h2>Register Now..!</h2>
        </div>
      </div>



    </div>
  </section>
<section id="contact" class="contact">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Register</h2>
            <div class="row mt-5">
              <div class="col-lg-8 mt-5 mt-lg-6">



            <form action="" method="post" role="form" class="">
              {% csrf_token %}
              <div class="row">
                <div class="col-md-8 form-group php-email-form">
                  <input type="text" name="username" class="form-control" id="username" placeholder="Username" required>
                </div>
                <div class="col-md-8 form-group mt-3 mt-md-4 php-email-form">
                  <input type="password" class="form-control" name="password" id="password" placeholder="Password" required>
                </div>
                <div class="col-md-8 form-group mt-3 mt-md-4 php-email-form">
                  <input type="password" class="form-control" name="cpassword" id="cpassword" placeholder="Confirm Password" required>
                </div>
              </div>
              <div class="php-email-form"><button type="submit">Submit</button></div>
              </form>

          </div>
        </div>
      </div>
      </div>
</section>
{% for msg in messages %}
  {{msg}}
{% endfor %}

{% endblock %}